[service: codeforces] ignore NavigableString from tag.children while downloading sample cases
Before this commit, downloading sample cases from codeforces was failing, probably
due to some format changes on codeforces website.

Following test cases were failing before this commit
```
FAILED tests/command_download_codeforces.py::DownloadCodeforcesTest::test_call_download_codeforces_contest_1080_a - subprocess.CalledProcessError: Command '['/home/nilesh/.python/py3/bin/...
FAILED tests/command_download_codeforces.py::DownloadCodeforcesTest::test_call_download_codeforces_contest_538_h - subprocess.CalledProcessError: Command '['/home/nilesh/.python/py3/bin/p...
FAILED tests/command_download_codeforces.py::DownloadCodeforcesTest::test_call_download_codeforces_gym_101020_a - subprocess.CalledProcessError: Command '['/home/nilesh/.python/py3/bin/py...
FAILED tests/command_download_codeforces.py::DownloadCodeforcesTest::test_call_download_codeforces_problemset_700_b - subprocess.CalledProcessError: Command '['/home/nilesh/.python/py3/bi...
```

Rest of the tests are as they were before.