#219: add a line to fail on type checking
$ mypy --ignore-missing-imports oj
onlinejudge/implementation/main.py:348: error: Incompatible types in assignment (expression has type "str", variable has type "int")